name: deploy_endpoint
on:
  push:
    branches: [ main ]
jobs:
  run: 
    runs-on: [ubuntu-latest]
    container: docker://ubuntu:22.04
    steps:
    - uses: actions/checkout@v2

     # Install Python and pip inside the container
    - name: Install Python and pip
      run: |
        apt-get update
        apt-get install -y python3 python3-pip  # Install Python 3 and pip

    # Install Node.js and npm
    - name: Install Node.js and npm
      run: |
        apt-get update
        apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
        apt-get install -y nodejs

    # Install Python Dependencies
    - name: Install Python Dependencies
      run: |
        pip3 install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests
        
    - name: Fire SageMaker Deployment
      id: sm_train
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        python3 deploy.py
